play_motion:
  controllers: [arm_controller, head_controller, torso_controller, hand_controller]
  motions:
    home:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.18, 0.21, 0.35, 0.1, 0.0, -1.57, 0.0, 0.0]
        time_from_start: 0.0
      - positions: [0.18, 0.21, 0.35, -0.20, 0.0, -1.57, 1.37, 0.0]
        time_from_start: 1.5
      - positions: [0.18, 0.20, 0.35, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 3.5
      - positions: [0.18, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 6.0
      - positions: [0.15, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 9.0
      meta:
        name: Home
        usage: demo
        description: 'Go home'

    unfold_arm:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.30, 0.21, 0.35, -0.2, 0.8, -1.57, 1.37, 0.0]
        time_from_start: 4.0
      - positions: [0.30, 0.21, -0.2, -2.2, 1.15, -1.57, 0.2, 0.0]
        time_from_start: 6.0
      meta:
        name: unfold_arm
        usage: demo
        description: 'unfold_arm'

    reach_floor:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.10, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      - positions: [0.10, 1.6, -0.55, -1.35, 1.40, -1.57, -0.07, 0.0]
        time_from_start: 3.0
      - positions: [0.07, 1.6, -0.55, 0, 1.03, -1.57, -0.07, 0.0]
        time_from_start: 7.0
      meta:
        name: Reach Floor
        usage: demo
        description: 'Reach floor'

    reach_max:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.10, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      - positions: [0.35, 0.9, 0.68, -3.16, 1.10, 2.05, 1.0, 0.0]
        time_from_start: 4.0
      - positions: [0.35, 0.9, 1.05, -3.45, 0.45, 2.05, 1.0, 0.0]
        time_from_start: 7.0
      meta:
        name: Reach Max
        usage: demo
        description: 'Reach max'

    open_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [-1.0, -1.0, -1.0]
        time_from_start: 0.1
      - positions: [0.0, 0.0, 0.0]
        time_from_start: 2.5
      meta:
        name: open_hand
        usage: demo
        description: 'open_hand'

    close_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [2.37, 0.0, 0.0]
        time_from_start: 0.1
      - positions: [6.2, 6.8, 9.2]
        time_from_start: 2.5
      meta:
        name: close_hand
        usage: demo
        description: 'close_hand'

    pointing_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [2.37, -1.0, 0.0]
        time_from_start: 0.1
      - positions: [6.2, 0.0, 9.2]
        time_from_start: 1.5
      meta:
        name: pointing_hand
        usage: demo
        description: 'pointing_hand'

    gun_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [-1.0, -1.0, 0.0]
        time_from_start: 0.1
      - positions: [0.0, 0.0, 9.2]
        time_from_start: 1.5
      meta:
        name: gun_hand
        usage: demo
        description: 'gun_hand'

    thumb_up_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [-1.0, 0.0, 0.0]
        time_from_start: 0.1
      - positions: [0.0, 6.8, 9.2]
        time_from_start: 1.5
      meta:
        name: thumb_up_hand
        usage: demo
        description: 'thumb_up_hand'

    pinch_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [0.0, -1.0, -1.0]
        time_from_start: 0.1
      - positions: [3.37, 4.0, 0.0]
        time_from_start: 1.5
      meta:
        name: pinch_hand
        usage: demo
        description: 'pinch_hand'

    head_tour:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, 0]
        time_from_start: 0.1
      - positions: [0.7, 0]
        time_from_start: 3.0
      - positions: [0.7, 0.3]
        time_from_start: 6.0
      - positions: [0.7, -0.3]
        time_from_start: 9.0
      - positions: [0.7, 0.3]
        time_from_start: 12.0
      - positions: [-0.7, 0.3]
        time_from_start: 15.0
      - positions: [-0.7, -0.3]
        time_from_start: 18.0
      - positions: [0, 0]
        time_from_start: 21.0
      meta:
        name: head_tour
        usage: demo
        description: 'head_tour'

    head_look_around:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, 0]
        time_from_start: 0.1
      - positions: [0, -0.7]
        time_from_start: 3.0
      - positions: [-0.7, -0.7]
        time_from_start: 6.0
      - positions: [-0.7, -0.5]
        time_from_start: 9.0
      - positions: [0, -0.5]
        time_from_start: 12.0
      - positions: [0.7, -0.5]
        time_from_start: 15.0
      - positions: [0.7, -0.7]
        time_from_start: 18.0
      - positions: [0, -0.7]
        time_from_start: 21.0
      - positions: [0, -0.5]
        time_from_start: 24.0
      meta:
        name: head_look_around
        usage: demo
        description: 'head_look_around'

    wave:
      joints: [arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint,
      arm_5_joint, arm_6_joint, arm_7_joint]
      points:
      - positions: [0.06337464909724033, -0.679638896132783, -3.1087325315620733, 2.0882339360702575, -1.1201172410014792, -0.031008601325809293, -2.0744261217334135]
        time_from_start: 0.0
      - positions: [0.06335930908588873, -0.7354151774072313, -2.939624246421942, 1.8341256735249563, -1.1201355028397157, -0.031008601325809293, -2.0744261217334135]
        time_from_start: 1.0
      - positions: [0.06335930908588873, -0.7231278283145929, -2.9385504456273295, 2.2121050027803877, -1.1201355028397157, -0.031008601325809293, -2.0744261217334135]
        time_from_start: 2.0
      - positions: [0.06335930908588873, -0.7354151774072313, -2.939624246421942, 1.8341256735249563, -1.1201355028397157, -0.031008601325809293, -2.0744261217334135]
        time_from_start: 3.0
      meta:
        name: Wave
        usage: demo
        description: 'wave'

    pregrasp_weight:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.10, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      meta:
        name: pregrasp_weight
        usage: demo
        description: 'Pregrasp weight'

    do_weights:
      joints: [arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 2.0
      - positions: [1.6, -0.90, -3.16, 2.0, -1.57, 0.35, 0.0]
        time_from_start: 4.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 6.0
      - positions: [1.6, -0.90, -3.16, 2.0, -1.57, 0.35, 0.0]
        time_from_start: 8.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 10.0
      - positions: [1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 12.0
      meta:
        name: do_weights
        usage: demo
        description: 'Do weights'

    offer_hand:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint', 'hand_thumb_joint', 'hand_index_joint', 'hand_mrl_joint']
      points:
      - positions: [0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.62, -1.577, -0.001, -0.0, -0.001]
        time_from_start: 0.0
      meta:
        name: offer_hand
        usage: demo
        description: 'offer_hand'

    shake_hands:
      joints: ['hand_thumb_joint','hand_index_joint','hand_mrl_joint','torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint']
      points:
      - positions: [0.0, 0.0, 0.0, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 0.0
      - positions: [6.2, 6.8, 9.2, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 5.0
      - positions: [6.2, 6.8, 9.2, 0.296, 1.61, -0.93, -3.14, 1.40, -1.577, -0.2, -1.577]
        time_from_start: 6.0
      - positions: [6.2, 6.8, 9.2, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 7.0
      - positions: [6.2, 6.8, 9.2, 0.296, 1.61, -0.93, -3.14, 1.40, -1.577, -0.2, -1.577]
        time_from_start: 8.0
      - positions: [6.2, 6.8, 9.2, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 9.0
      - positions: [0.0, 0.0, 0.0, 0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.53, -1.577]
        time_from_start: 11.0
      meta:
        name: shake_hands
        usage: demo
        description: 'shake_hands'

    pick_from_floor:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint', 'hand_thumb_joint', 'hand_index_joint', 'hand_mrl_joint']
      points:
      - positions: [0.226, 0.308, -0.695, -0.968, 1.582,  1.965, 0.273, -1.101, 0.0, -0.001, -0.0]
        time_from_start: 0.0
      - positions: [0.0, 0.809, -1.197, -1.119, 0.322, 1.96, -0.849, 0.041, 0.0, -0.001, -0.0]
        time_from_start: 4.0
      - positions: [0.0, 0.809, -1.197, -1.119, 0.345, 1.96, -0.849, 0.041, 6.2, 6.77, 8.8]
        time_from_start: 6.0
      - positions: [0.158, 0.21, -1.153, -1.538, 2.306, 1.965, 0.394, -0.082, 6.2, 6.77, 8.8]
        time_from_start: 9.0
      meta:
        name: pick_from_floor
        usage: demo
        description: 'Pick a shirt-like object from floor in front of the robot'
