joy_teleop:
  ros__parameters:

    close_hand:
      type: action
      interface_type: play_motion2_msgs/action/PlayMotion2
      action_name: /play_motion2
      action_goal:
        motion_name: 'close'
        skip_planning: True
      buttons: [2, 6]

    open_hand:
      type: action
      interface_type: play_motion2_msgs/action/PlayMotion2
      action_name: /play_motion2
      action_goal:
        motion_name: 'open'
        skip_planning: True
      buttons: [2, 4]

