joy_teleop:
  ros__parameters:

    close_gripper:
      type: action
      interface_type: teleop_tools_msgs/action/Increment
      action_name: /gripper_controller/increment
      action_goal:
        increment_by: [-0.01, -0.01]
      buttons: [1]
      axes_negative: [5]

    open_gripper:
      type: action
      interface_type: teleop_tools_msgs/action/Increment
      action_name: /gripper_controller/increment
      action_goal:
        increment_by: [0.01, 0.01]
      buttons: [0]
      axes_negative: [5]


