#!/usr/bin/env python3
import em
import sys
import os


em_file_path = sys.argv[1]

no_em_extension_path = os.path.splitext(em_file_path)[0]
no_extension_path = os.path.splitext(no_em_extension_path)[0]
extension = os.path.splitext(no_em_extension_path)[1]

for arm in ['right-arm', 'no-arm']:  # 'left-arm',  unsupported yet
    if arm != 'no-arm':
        end_effectors = ["pal-hey5", "pal-gripper", "schunk-wsg", "custom"]
        ft_sensors = ["schunk-ft", 'no-ft-sensor']
    else:
        end_effectors = ['no-end-effector']
        ft_sensors = ['no-ft-sensor']
    for end_effector in end_effectors:
        for ft_sensor in ft_sensors:
            cfg = {
                "has_arm": arm != 'no-arm',
                "end_effector": end_effector,
                "ft_sensor": ft_sensor,
            }
            with open(em_file_path, "r") as f:
                expanded_contents = em.expand(f.read(), cfg)
            suffix = "_{}_{}_{}".format(arm, end_effector, ft_sensor)
            expanded_file_name = no_extension_path + suffix + extension
            with open(expanded_file_name, "w") as f:
                msg = "Autogenerated file, don't edit this, edit {} instead".format(
                    os.path.basename(em_file_path))
                if extension == ".yaml":
                    f.write("#" + msg + "\n")
                elif extension in [".xacro", ".xml"]:
                    f.write("<!-- " + msg + "-->\n")

                f.write(expanded_contents)
            print("Generated " + expanded_file_name)
