arm_forward_velocity_controller:
  type: "velocity_controllers/JointGroupVelocityController"
  joints:
    - arm_1_joint
    - arm_2_joint
    - arm_3_joint
    - arm_4_joint
    - arm_5_joint
    - arm_6_joint
    - arm_7_joint
