<?xml version="1.0"?>

<!--
  Copyright (c) 2011, PAL Robotics, S.L.
  All rights reserved.

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ant_description)/urdf/wheels/caster.transmission.xacro"/>
  <xacro:include filename="$(find ant_description)/urdf/wheels/caster.gazebo.xacro"/>

  <xacro:macro name="caster" params="side radius width separation_x separation_y offset_z parent">
    <link name="caster_${side}_1_link">
      <inertial>
        <origin xyz="-0.00653 -0.00008 -0.01177" rpy="0 0 0"/>
        <mass value="0.09556"/>
        <inertia  ixx="0.00002195406" ixy="0.00000000009" ixz="0.00000370909"
                  iyy="0.00001717745" iyz="-0.00000000032"
                  izz="0.00002240463"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <!--box size="${radius} ${1.2 * width} ${radius}"/-->
          <mesh filename="package://ant_description/meshes/wheels/caster.stl"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <!--box size="${radius} ${1.2 * width} ${radius}"/-->
          <mesh filename="package://ant_description/meshes/wheels/caster.stl"/>
        </geometry>
      </collision>
    </link>

    <link name="caster_${side}_2_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.02425"/>
        <inertia  ixx="0.00000464376" ixy="0" ixz="0"
                  iyy="0.00000464377" iyz="0"
                  izz="0.00000802779"/>
        </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
        <material name="DarkGrey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu> 0.01</mu>
              <mu2>0.01</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
    </link>

    <joint name="caster_${side}_1_joint" type="continuous">
      <parent link="${parent}_link"/>
      <child link="caster_${side}_1_link"/>
      <origin xyz="${separation_x / 2} ${-separation_y / 2} ${offset_z}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <joint name="caster_${side}_2_joint" type="continuous">
      <parent link="caster_${side}_1_link"/>
      <child link="caster_${side}_2_link"/>
      <origin xyz="-0.017 0.0003 -0.032" rpy="${-90.0 * deg_to_rad} 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>

    <!-- Transmission -->
    <!--xacro:caster_transmission name="" side="${side}" number="" reduction=""-->

    <!-- Gazebo extensions -->
    <xacro:caster_gazebo side="${side}"/>
  </xacro:macro>
</robot>
