<?xml version="1.0"?>

<!--
  Copyright (c) 2011, PAL Robotics, S.L.
  All rights reserved.

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ant_description)/urdf/wheels/wheel.transmission.xacro"/>
  <xacro:include filename="$(find ant_description)/urdf/wheels/wheel.gazebo.xacro"/>

  <xacro:macro name="wheel" params="side reflect radius width torque velocity separation parent">
    <link name="wheel_${side}_link">
      <inertial>
        <origin xyz="0 0 -0.0016" rpy="0 0 0"/>
        <mass value="3.33926"/>
        <inertia ixx="0.00668369447" ixy="0.00000007414" ixz="0.00000024433"
                 iyy="0.00668332554" iyz="-0.00000005662"
                 izz="0.01088090651"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
        <material name="LightGrey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu> 0.01</mu>
              <mu2>0.01</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
    </link>

    <joint name="wheel_${side}_joint" type="continuous">
      <parent link="${parent}_link"/>
      <child link="wheel_${side}_link"/>
      <origin xyz="0 ${-separation / 2 * reflect} 0" rpy="${-90.0 * deg_to_rad} 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="${torque}" velocity="${velocity / radius}"/>
    </joint>

    <!-- Transmission -->
    <xacro:wheel_transmission side="${side}"/>

    <!-- Gazebo extensions -->
    <xacro:wheel_gazebo side="${side}"/>
  </xacro:macro>
</robot>
